name = "Techblog Theme"
license = "MIT"
licenselink = "https://github.com/parthw/hugo-techblog-theme/blob/master/LICENSE"
description = "Minimal Techblog Theme for Engineers"
homepage = "https://parthw.github.io"
tags = ["minimal", "blog", "personal", "clean", "simple", "starter", "minimalist"]
features = ["blog"]
min_version = "0.1"

[author]
  name = "Parth Wadhwa"
  homepage = "https://parthw.github.io"
